### ISSUE TITLE
Copy 0B files is slow and then crashes

### ISSUE THREAD

**Issue by EmmanuelMess** [arpitkh96/AmazeFileManager#1380]
* Copying 1001 files 0B files in sd I didn't see more than one line, although the notification was missing (also, files seem to be copied at 1 every ~4s, wut?)... and it crashed (after 179 files):
```
07-29 15:50:24.365 com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager, PID: 31173
    java.lang.RuntimeException: Unable to start service com.amaze.filemanager.asynchronous.services.CopyService@33ad6bc with null: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3045)
        at android.app.ActivityThread.-wrap17(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
        at com.amaze.filemanager.asynchronous.services.CopyService.onStartCommand(CopyService.java:107)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3028)
        at android.app.ActivityThread.-wrap17(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```
* Retying the 1001 file copy, no notifications is shown and it is really slow, (around 1hr to copy 860, 0B, files), when I opened the cronometer app by accident Amaze crashed:
```
07-29 16:58:38.495 com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager, PID: 6041
    java.lang.RuntimeException: Unable to start service com.amaze.filemanager.asynchronous.services.CopyService@33ad6bc with null: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3045)
        at android.app.ActivityThread.-wrap17(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
        at com.amaze.filemanager.asynchronous.services.CopyService.onStartCommand(CopyService.java:107)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3028)
        at android.app.ActivityThread.-wrap17(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by VishalNehra** [comment]
From #1372  
> Nope, run touch {0..1000}.jpg.

Who the hell copies 1001 files with 0Bytes size at once? 
Can't fix a 
> intent.getBooleanExtra(TAG_IS_ROOT_EXPLORER ,false) 

pointing to a null ````intent````. The intent is clearly provided by android system callback ````onStartCommand(Intent intent, int flags, final int startId)````.

**Comment by EmmanuelMess** [comment]
> Who the hell copies 1001 files with 0Bytes size at once?

This should be fixed, maybe is low priority, but not "wontfix", this is a file manager...

> Can't fix a
>>    intent.getBooleanExtra(TAG_IS_ROOT_EXPLORER ,false)

Will try to find solution.

**Comment by EmmanuelMess** [comment]
From the [documentation](https://developer.android.com/reference/android/app/Service#onStartCommand(android.content.Intent,%20int,%20int)):

> Intent: The Intent supplied to Context.startService(Intent),   as given.  This may be null if the service is being restarted after  its process has gone away, and it had previously returned anything  except START_STICKY_COMPATIBILITY.
