### ISSUE TITLE
not run on Device

### ISSUE THREAD

**Issue by danhantao** [arpitkh96/AmazeFileManager#257]
05-13 17:27:51.367 22714-22714/com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.amaze.filemanager, PID: 22714
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: java.lang.NullPointerException
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.NullPointerException
                                                                           at com.amaze.filemanager.activities.MainActivity.initialiseViews(MainActivity.java:1909)
                                                                           at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:250)

Device: Nexus 5    4.4.2

**Comment by vishal0071** [comment]
Were you able to solve it?
