### ISSUE TITLE
Crash after update from 3.0.1 to 3.1.0

### ISSUE THREAD

**Issue by ByteHamster** [arpitkh96/AmazeFileManager#281]
Using Play Store version 

```
D/AndroidRuntime( 7960): Shutting down VM
E/AndroidRuntime( 7960): FATAL EXCEPTION: main
E/AndroidRuntime( 7960): Process: com.amaze.filemanager, PID: 7960
E/AndroidRuntime( 7960): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
E/AndroidRuntime( 7960): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
E/AndroidRuntime( 7960): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2419)
E/AndroidRuntime( 7960): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime( 7960): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 7960): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7960): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7960): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime( 7960): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7960): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7960): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 7960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 7960): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
E/AndroidRuntime( 7960): Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
E/AndroidRuntime( 7960): 	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:239)
E/AndroidRuntime( 7960): 	at com.amaze.filemanager.utils.PreferenceUtils.getPrimaryColor(PreferenceUtils.java:69)
E/AndroidRuntime( 7960): 	at com.amaze.filemanager.utils.PreferenceUtils.getPrimaryColorString(PreferenceUtils.java:89)
E/AndroidRuntime( 7960): 	at com.amaze.filemanager.activities.BaseActivity.onCreate(BaseActivity.java:50)
E/AndroidRuntime( 7960): 	at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:255)
E/AndroidRuntime( 7960): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 7960): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 7960): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2310)
E/AndroidRuntime( 7960): 	... 11 more
W/ActivityManager( 2471):   Force finishing activity 1 com.amaze.filemanager/.activities.MainActivity

```

**Comment by vishal0071** [comment]
Try reinstalling amaze from play store.

**Comment by ByteHamster** [comment]
I know I can do that but I guess there are more people out there who suffer from this crash. It might be better to fix it instead of telling everyone to reinstall (and set the options again)

**Comment by vishal0071** [comment]
The only way to fix would be to programatically wipe data as the app opens, instead for a user to wipe it manually.
