### ISSUE TITLE
Crash when switching to recents

### ISSUE THREAD

**Issue by ByteHamster** [arpitkh96/AmazeFileManager#296]
Using 3.1.0 from Google Play on cm12.1. Amaze crashes when switching to recent apps while Amaze is opened. 

```
D/AndroidRuntime(32407): Shutting down VM
E/AndroidRuntime(32407): FATAL EXCEPTION: main
E/AndroidRuntime(32407): Process: com.amaze.filemanager, PID: 32407
E/AndroidRuntime(32407): java.lang.ClassCastException: android.support.v4.graphics.drawable.DrawableWrapperLollipop cannot be cast to android.graphics.drawable.BitmapDrawable
E/AndroidRuntime(32407): 	at com.amaze.filemanager.ui.Layoutelements.writeToParcel(Layoutelements.java:75)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeParcelable(Parcel.java:1363)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeValue(Parcel.java:1268)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeList(Parcel.java:717)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeValue(Parcel.java:1290)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
E/AndroidRuntime(32407): 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
E/AndroidRuntime(32407): 	at android.os.Bundle.writeToParcel(Bundle.java:1034)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeBundle(Parcel.java:669)
E/AndroidRuntime(32407): 	at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:138)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeTypedArray(Parcel.java:1197)
E/AndroidRuntime(32407): 	at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:385)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeParcelable(Parcel.java:1363)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeValue(Parcel.java:1268)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
E/AndroidRuntime(32407): 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
E/AndroidRuntime(32407): 	at android.os.Bundle.writeToParcel(Bundle.java:1034)
E/AndroidRuntime(32407): 	at android.os.Parcel.writeBundle(Parcel.java:669)
E/AndroidRuntime(32407): 	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2942)
E/AndroidRuntime(32407): 	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3328)
E/AndroidRuntime(32407): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(32407): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(32407): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(32407): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime(32407): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32407): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32407): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(32407): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(32407): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by ByteHamster** [comment]
Same crash happens when trying to open a file. Looks like a problem when pausing the app

**Comment by steve95** [comment]
Same here: https://github.com/arpitkh96/AmazeFileManager/issues/289

**Comment by vishal0071** [comment]
I'll look into it.

**Comment by Tony-il-Capo** [comment]
As mentioned here [#289](https://github.com/arpitkh96/AmazeFileManager/issues/289) I have the exact same problem.
