### ISSUE TITLE
Crash on Device Rotation

### ISSUE THREAD

**Issue by theck13** [arpitkh96/AmazeFileManager#353]
### Expected

The app does not crash when you rotate the device either portrait to landscape or landscape to portrait.
### Observed

The app crashes when the device is rotated either portrait to landscape or landscape to portrait immediately after launch.  The steps to reproduce the issue and stack trace are below.
#### Steps
1. Open the app.
2. Rotate the device.
3. Notice the crash.

```
10-28 13:54:28.957 519-519/com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager, PID: 519
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amaze.filemanager.utils.color.ColorPreference.getColorAsString(com.amaze.filemanager.utils.color.ColorUsage)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2649)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4486)
        at android.app.ActivityThread.-wrap19(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6088)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amaze.filemanager.utils.color.ColorPreference.getColorAsString(com.amaze.filemanager.utils.color.ColorUsage)' on a null object reference
        at com.amaze.filemanager.fragments.Main.onCreate(Main.java:205)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:1951)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2041)
        at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:163)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:332)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
        at com.amaze.filemanager.activities.BasicActivity.onCreate(BasicActivity.java:30)
        at com.amaze.filemanager.activities.BaseActivity.onCreate(BaseActivity.java:38)
        at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:241)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2602)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4486) 
        at android.app.ActivityThread.-wrap19(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6088) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```
#### Tested

Google Pixel on Android 7.1 with Amaze File Manager 3.1.2 Beta 2

**Comment by vishal0071** [comment]
Wow, Google Pixel! (: 
Can't reproduce it BTW. Chances are, it's already been fixed. I'll publish another beta soon, test it then report back.

**Comment by rpiotaix** [comment]
Nope.
Can reproduce it with master.
It seems that its because 'getColorAsString' is called before onCreate on the MainActivity which initialize ColorPreference...
Working on a fix, will post a PR soon.

**Comment by rpiotaix** [comment]
Motre info:

The problem is on TabFragment.
Two possibilities:
- The application is suspended (savedInstanceState == null): it works
- The application has to be "launched from scratch"

When launched from scratch and the screen is tilted, two things happen:
the onCreate method is called and then (if the screen is tilted since the begining) the onSaveInstanceState method is called. this method saves the tabs statuses to the outState Bundle (which is used to restore the app from).
The the layout of the app switch to the landscape one and the status is restored.

Problem is: the tabs are initialized in the onCreateView method which is not called. Thos implies, no tabs are saved in the Bundle, none are loaded after layout change and when trying to display them, a null pointer is returned.

**Comment by theck13** [comment]
How about initializing the tabs in the `onActivityCreated` method and restore from the saved `Bundle` if it's not `null`?
