### ISSUE TITLE
It crashes

### ISSUE THREAD

**Issue by KOLANICH** [arpitkh96/AmazeFileManager#373]
```
--------- beginning of /dev/log/main
D/su      ( 5029): 0 /system/bin/mksh executing 10082 logcat -f using binary /system/bin/sh : sh -c logcat -f
D/su      ( 5046): 0 /system/bin/mksh executing 10082 logcat using binary /system/bin/sh : sh -c logcat
W/XPrivacy( 5052): Hooking package=com.amaze.filemanager
D/ActivityThread( 5052): handleBindApplication:com.amaze.filemanager
D/ActivityThread( 5052): setTargetHeapUtilization:0.75
D/ActivityThread( 5052): setTargetHeapMinFree:2097152
I/dalvikvm( 5052): Could not find method android.view.ViewAnimationUtils.createCircularReveal, referenced from method com.amaze.filemanager.activities.MainActivity.hideSearchView
W/dalvikvm( 5052): VFY: unable to resolve static method 19235: Landroid/view/ViewAnimationUtils;.createCircularReveal (Landroid/view/View;IIFF)Landroid/animation/Animator;
D/dalvikvm( 5052): VFY: replacing opcode 0x71 at 0x002b
I/dalvikvm( 5052): Could not find method android.view.Window.setStatusBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.initialiseViews
W/dalvikvm( 5052): VFY: unable to resolve virtual method 19453: Landroid/view/Window;.setStatusBarColor (I)V
D/dalvikvm( 5052): VFY: replacing opcode 0x6e at 0x02ee
I/dalvikvm( 5052): Could not find method android.view.Window.setNavigationBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.initialiseViews
W/dalvikvm( 5052): VFY: unable to resolve virtual method 19452: Landroid/view/Window;.setNavigationBarColor (I)V
D/dalvikvm( 5052): VFY: replacing opcode 0x6e at 0x02f7
E/dalvikvm( 5052): Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.amaze.filemanager.activities.MainActivity.onCreate
W/dalvikvm( 5052): VFY: unable to resolve new-instance 25 (Landroid/app/ActivityManager$TaskDescription;) in Lcom/amaze/filemanager/activities/MainActivity;
D/dalvikvm( 5052): VFY: replacing opcode 0x22 at 0x01ed
I/dalvikvm( 5052): Could not find method android.support.v7.widget.Toolbar.setElevation, referenced from method com.amaze.filemanager.activities.MainActivity.onPrepareOptionsMenu
W/dalvikvm( 5052): VFY: unable to resolve virtual method 18372: Landroid/support/v7/widget/Toolbar;.setElevation (F)V
D/dalvikvm( 5052): VFY: replacing opcode 0x6e at 0x0083
I/dalvikvm( 5052): Could not find method android.view.ViewAnimationUtils.createCircularReveal, referenced from method com.amaze.filemanager.activities.MainActivity.revealSearchView
W/dalvikvm( 5052): VFY: unable to resolve static method 19235: Landroid/view/ViewAnimationUtils;.createCircularReveal (Landroid/view/View;IIFF)Landroid/animation/Animator;
D/dalvikvm( 5052): VFY: replacing opcode 0x71 at 0x002b
I/dalvikvm( 5052): Could not find method android.view.Window.setStatusBarColor, referenced from method com.amaze.filemanager.activities.MainActivity.updateViews
W/dalvikvm( 5052): VFY: unable to resolve virtual method 19453: Landroid/view/Window;.setStatusBarColor (I)V
D/dalvikvm( 5052): VFY: replacing opcode 0x6e at 0x003a
D/dalvikvm( 5052): DexOpt: unable to opt direct call 0x008a at 0x20c in Lcom/amaze/filemanager/activities/MainActivity;.onCreate
W/dalvikvm( 5052): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm( 5052): Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
W/dalvikvm( 5052): VFY: unable to resolve interface method 19433: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm( 5052): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm( 5052): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
W/dalvikvm( 5052): VFY: unable to resolve interface method 19437: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm( 5052): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm( 5052): Could not find method android.widget.CheckBox.setButtonTintList, referenced from method com.amaze.filemanager.utils.Futils.setTint
W/dalvikvm( 5052): VFY: unable to resolve virtual method 19804: Landroid/widget/CheckBox;.setButtonTintList (Landroid/content/res/ColorStateList;)V
D/dalvikvm( 5052): VFY: replacing opcode 0x6e at 0x0033
I/dalvikvm( 5052): Could not find method android.widget.EditText.setBackgroundTintList, referenced from method com.amaze.filemanager.utils.Futils.setTint
W/dalvikvm( 5052): VFY: unable to resolve virtual method 19887: Landroid/widget/EditText;.setBackgroundTintList (Landroid/content/res/ColorStateList;)V
D/dalvikvm( 5052): VFY: replacing opcode 0x6e at 0x0019
I/dalvikvm( 5052): Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
W/dalvikvm( 5052): VFY: unable to resolve virtual method 553: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
D/dalvikvm( 5052): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm( 5052): Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
W/dalvikvm( 5052): VFY: unable to resolve virtual method 575: Landroid/content/res/TypedArray;.getType (I)I
D/dalvikvm( 5052): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm( 5052): Could not find method android.widget.ImageButton.<init>, referenced from method com.github.clans.fab.FloatingActionButton.<init>
W/dalvikvm( 5052): VFY: unable to resolve direct method 19973: Landroid/widget/ImageButton;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
D/dalvikvm( 5052): VFY: replacing opcode 0x70 at 0x0003
W/dalvikvm( 5052): Unable to resolve superclass of Lcom/github/clans/fab/FloatingActionButton$1; (2252)
W/dalvikvm( 5052): Link of class 'Lcom/github/clans/fab/FloatingActionButton$1;' failed
E/dalvikvm( 5052): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.FloatingActionButton.createFillDrawable
W/dalvikvm( 5052): VFY: unable to resolve new-instance 158 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/FloatingActionButton;
D/dalvikvm( 5052): VFY: replacing opcode 0x22 at 0x0038
E/dalvikvm( 5052): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.FloatingActionButton.onActionDown
W/dalvikvm( 5052): VFY: unable to resolve check-cast 158 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/FloatingActionButton;
D/dalvikvm( 5052): VFY: replacing opcode 0x1f at 0x001d
E/dalvikvm( 5052): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.FloatingActionButton.onActionUp
W/dalvikvm( 5052): VFY: unable to resolve check-cast 158 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/FloatingActionButton;
D/dalvikvm( 5052): VFY: replacing opcode 0x1f at 0x001f
I/dalvikvm( 5052): Could not find method android.widget.ImageButton.setElevation, referenced from method com.github.clans.fab.FloatingActionButton.setElevation
W/dalvikvm( 5052): VFY: unable to resolve virtual method 19990: Landroid/widget/ImageButton;.setElevation (F)V
D/dalvikvm( 5052): VFY: replacing opcode 0x6f at 0x000b
I/dalvikvm( 5052): Could not find method android.widget.ImageButton.setElevation, referenced from method com.github.clans.fab.FloatingActionButton.setElevationCompat
W/dalvikvm( 5052): VFY: unable to resolve virtual method 19990: Landroid/widget/ImageButton;.setElevation (F)V
D/dalvikvm( 5052): VFY: replacing opcode 0x6f at 0x0023
W/dalvikvm( 5052): Unable to resolve superclass of Lcom/github/clans/fab/FloatingActionButton$1; (2252)
W/dalvikvm( 5052): Link of class 'Lcom/github/clans/fab/FloatingActionButton$1;' failed
D/dalvikvm( 5052): DexOpt: unable to opt direct call 0x0390 at 0x4c in Lcom/github/clans/fab/FloatingActionButton;.createFillDrawable
W/dalvikvm( 5052): Unable to resolve superclass of Lcom/github/clans/fab/FloatingActionButton$1; (2252)
W/dalvikvm( 5052): Link of class 'Lcom/github/clans/fab/FloatingActionButton$1;' failed
D/dalvikvm( 5052): DexOpt: unable to opt direct call 0x5b4c at 0x51 in Lcom/github/clans/fab/FloatingActionButton;.createFillDrawable
E/dalvikvm( 5052): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.Label.createFillDrawable
W/dalvikvm( 5052): VFY: unable to resolve new-instance 158 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/Label;
D/dalvikvm( 5052): VFY: replacing opcode 0x22 at 0x0028
E/dalvikvm( 5052): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.Label.onActionDown
W/dalvikvm( 5052): VFY: unable to resolve instanceof 158 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/Label;
D/dalvikvm( 5052): VFY: replacing opcode 0x20 at 0x0029
E/dalvikvm( 5052): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.github.clans.fab.Label.onActionUp
W/dalvikvm( 5052): VFY: unable to resolve instanceof 158 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/github/clans/fab/Label;
D/dalvikvm( 5052): VFY: replacing opcode 0x20 at 0x0024
W/dalvikvm( 5052): Unable to resolve superclass of Lcom/github/clans/fab/Label$1; (2252)
W/dalvikvm( 5052): Link of class 'Lcom/github/clans/fab/Label$1;' failed
D/dalvikvm( 5052): DexOpt: unable to opt direct call 0x0390 at 0x3c in Lcom/github/clans/fab/Label;.createFillDrawable
W/dalvikvm( 5052): Unable to resolve superclass of Lcom/github/clans/fab/Label$1; (2252)
W/dalvikvm( 5052): Link of class 'Lcom/github/clans/fab/Label$1;' failed
D/dalvikvm( 5052): DexOpt: unable to opt direct call 0x5c72 at 0x41 in Lcom/github/clans/fab/Label;.createFillDrawable
D/TabFragment( 5052): Page Selected: 1
W/FragmentManager( 5052): moveToState: Fragment state for Main{423f0bf8 #2 id=0x7f0f0171} not updated inline; expected state 3 found 2
D/libEGL  ( 5052): loaded /system/lib/egl/libEGL_mali.so
D/libEGL  ( 5052): loaded /system/lib/egl/libGLESv1_CM_mali.so
D/libEGL  ( 5052): loaded /system/lib/egl/libGLESv2_mali.so
E/        ( 5052): Device driver API match
E/        ( 5052): Device driver API version: 23
E/        ( 5052): User space API version: 23 
E/        ( 5052): mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Fri Mar 21 13:52:50 KST 2014 
D/OpenGLRenderer( 5052): Enabling debug mode 0
E/RecyclerView( 5052): No adapter attached; skipping layout
E/RecyclerView( 5052): No adapter attached; skipping layout
W/View    ( 5052): requestLayout() improperly called by android.widget.FrameLayout{421152b8 V.E..... ......ID 0,96-1280,240 #7f0f00fe app:id/buttonbarframe} during layout: running second layout pass
W/View    ( 5052): requestLayout() improperly called by android.support.v7.widget.Toolbar{42109688 V.E..... ......ID 0,0-1280,96 #7f0f0060 app:id/action_bar} during layout: running second layout pass
W/View    ( 5052): requestLayout() improperly called by android.view.View{424df778 V.ED.... ......I. 0,0-0,0} during layout: running second layout pass
E/RecyclerView( 5052): No adapter attached; skipping layout
E/RecyclerView( 5052): No adapter attached; skipping layout
E/RecyclerView( 5052): No adapter attached; skipping layout
E/RecyclerView( 5052): No adapter attached; skipping layout
I/Timeline( 5052): Timeline: Activity_idle id: android.os.BinderProxy@42068990 time:1561348
W/IInputConnectionWrapper( 5052): showStatusIcon on inactive InputConnection
D/AndroidRuntime( 5052): Shutting down VM
W/dalvikvm( 5052): threadid=1: thread exiting with uncaught exception (group=0x4184cce0)
--------- beginning of /dev/log/system
E/AndroidRuntime( 5052): FATAL EXCEPTION: main
E/AndroidRuntime( 5052): Process: com.amaze.filemanager, PID: 5052
E/AndroidRuntime( 5052): java.lang.ClassCastException: android.support.v4.graphics.drawable.DrawableWrapperKitKat cannot be cast to android.graphics.drawable.BitmapDrawable
E/AndroidRuntime( 5052): 	at com.amaze.filemanager.ui.Layoutelements.writeToParcel(Layoutelements.java:75)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeParcelable(Parcel.java:1292)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeValue(Parcel.java:1211)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeList(Parcel.java:660)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeValue(Parcel.java:1233)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
E/AndroidRuntime( 5052): 	at android.os.Bundle.writeToParcel(Bundle.java:1692)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeBundle(Parcel.java:643)
E/AndroidRuntime( 5052): 	at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:138)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeTypedArray(Parcel.java:1140)
E/AndroidRuntime( 5052): 	at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:385)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeParcelable(Parcel.java:1292)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeValue(Parcel.java:1211)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
E/AndroidRuntime( 5052): 	at android.os.Bundle.writeToParcel(Bundle.java:1692)
E/AndroidRuntime( 5052): 	at android.os.Parcel.writeBundle(Parcel.java:643)
E/AndroidRuntime( 5052): 	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2488)
E/AndroidRuntime( 5052): 	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3122)
E/AndroidRuntime( 5052): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 5052): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5052): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5052): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime( 5052): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5052): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5052): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime( 5052): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime( 5052): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime( 5052): 	at dalvik.system.NativeStart.main(Native Method)
I/Process ( 5052): Sending signal. PID: 5052 SIG: 9
```

**Comment by vishal0071** [comment]
It's been fixed already, try latest beta from play store or AFH

**Comment by KOLANICH** [comment]
How about f-droid?

**Comment by vishal0071** [comment]
I'm sorry, fdroid doesn't have any beta testing platform so you gotta wait for a stable build.

**Comment by KOLANICH** [comment]
In fact it has. Some apps are marked as unstable and there is a flag in the settings to update to unstable versions.

**Comment by vishal0071** [comment]
If that's the case, I'll look into it. Thanks for informing.

**Comment by maverick74** [comment]
I'm sorry to say that I'm using 3.1.2 beta 5 and it still crashes. Every time i, for example, try to create a new folder...

**Comment by markybob** [comment]
same. still crashes all the time on 7.1.1 DP2. i'm sending bug reports when it does via "send feedback" so hopefully that's making it to the right people

**Comment by maverick74** [comment]
Well, at least it ain't just me.

Please consider reopening it...

**Comment by maverick74** [comment]
Well, at least it ain't just me.

Please consider reopening it...

**Comment by KOLANICH** [comment]
@vishal0071

**Comment by vishal0071** [comment]
@KOLANICH I created a beta release long before (v3.1.2 beta 8). Fdroid never published it, even as unstable. 
But I also push apk on AFH for fdroid so you need to download from there.
I skipped v3.1.2 beta 9 but this next update will come for fdroid too.
I can only promise AFH and I guess I'll talk to fdroid guys about this.

**Comment by Alexander--** [comment]
@vishal0071 From my experience, F-Droid maintainers never actually  bother with *maintaining* anything. Unless one of them is especially invested into the app, they won't even fix trivial build failures. There is an automatic publishing support, but as soon as the builds fails, or the app is discovered to contain any suspiciously-looking binaries, it is usually disabled. The publishing of Amaze was disabled in [this commit](https://gitlab.com/fdroid/fdroiddata/commit/465f3bb04a9c3427d89cc7669dd931a184c634e5).

The only reliable way to publish anything in F-Droid is keeping in touch with them and manually submitting pull-requests to their metadata repository when necessary.
