### ISSUE TITLE
Random crash of GUI after rotating phone from portrait to landscape... (Automatic crash report dump)

### ISSUE THREAD

**Issue by Benjamin-6848** [arpitkh96/AmazeFileManager#4098]
## Issue explanation (write below this line)

Random crash of GUI after rotating phone from portrait to landscape... (Automatic crash report dump)

## Exception
* __App Name:__ Amaze Dateimanager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ TANK3
* __Model:__ TANK 3
* __Product:__ TANK3
<details><summary><b>Crash log </b></summary><p>

```
kotlin.UninitializedPropertyAccessException: lateinit property compressedFile has not been initialized
	at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.getCompressedFile(CompressedExplorerFragment.kt:96)
	at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.onSaveInstanceState(CompressedExplorerFragment.kt:341)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3183)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:646)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2318)
	at androidx.fragment.app.FragmentManager.lambda$attachController$0(FragmentManager.java:2572)
	at androidx.fragment.app.FragmentManager.$r8$lambda$XfPeDpLzKWrJr916TDyhue4S3eM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda0.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:338)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1280)
	at android.app.Activity.performSaveInstanceState(Activity.java:2212)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1563)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5847)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5245)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5801)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5719)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3390 & fixed with #3351
