### ISSUE TITLE
`TransactionTooLargeException` when deleting

### ISSUE THREAD

**Issue by Cmac299203** [arpitkh96/AmazeFileManager#4103]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/x1qcsx/x1q:13/TP1A.220624.014/G981WVLU6HWHA:user/release-keys 13 - 33
* __Device:__ x1q
* __Model:__ SM-G981W
* __Product:__ x1qcsx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1032052 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:88)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.os.TransactionTooLargeException: data parcel size 1032052 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:662)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1309)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:85)
	... 9 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3078

**Comment by VishnuSanal** [comment]
similar https://github.com/TeamAmaze/AmazeFileManager/issues/3078
