### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by scruel** [arpitkh96/AmazeFileManager#4112]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ cas
* __Model:__ M2007J1SC
* __Product:__ cas
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:82)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
  ComposedException 1 :
	org.apache.commons.compress.archivers.ArchiveException: Zip file is corrupt
		at com.amaze.filemanager.asynchronous.asynctasks.compress.ZipHelperCallable.addElements(ZipHelperCallable.kt:129)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperCallable.call(CompressedHelperCallable.kt:42)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperCallable.call(CompressedHelperCallable.kt:29)
		at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:39)
		at io.reactivex.Flowable.subscribe(Flowable.java:14826)
		at io.reactivex.Flowable.subscribe(Flowable.java:14773)
		at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
		at java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
		at java.lang.Thread.run(Thread.java:1012)
	Caused by: net.lingala.zip4j.exception.ZipException: Zip file size less than minimum expected zip file size. Probably not a zip file or a corrupted zip file
		at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:68)
		at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:971)
		at net.lingala.zip4j.ZipFile.getFileHeaders(ZipFile.java:559)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.ZipHelperCallable.filterValidEntryList(ZipHelperCallable.kt:134)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.ZipHelperCallable.addElements(ZipHelperCallable.kt:54)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperCallable.call(CompressedHelperCallable.kt:42)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperCallable.call(CompressedHelperCallable.kt:29)
		at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:39)
		at io.reactivex.Flowable.subscribe(Flowable.java:14826)
		at io.reactivex.Flowable.subscribe(Flowable.java:14773)
		at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
		at java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
		at java.lang.Thread.run(Thread.java:1012)
	Caused by: java.lang.IllegalStateException: Fragment CompressedExplorerFragment{cce80c} (38d5b889-6a28-4dc2-b757-435e42c15ce4) not attached to a context.
		at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.archiveCorruptOrUnsupportedToast(CompressedExplorerFragment.kt:622)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.changePath$lambda-22$lambda-21(CompressedExplorerFragment.kt:583)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.$r8$lambda$fmscQU9YC5gGBMgAcmdKIXMPl08(Unknown Source:0)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment$$ExternalSyntheticLambda6.accept(Unknown Source:6)
		at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
		at android.os.Handler.handleCallback(Handler.java:942)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:211)
		at android.os.Looper.loop(Looper.java:300)
		at android.app.ActivityThread.main(ActivityThread.java:8401)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
  ComposedException 2 :
	java.lang.IllegalStateException: Fragment CompressedExplorerFragment{cce80c} (38d5b889-6a28-4dc2-b757-435e42c15ce4) not attached to a context.
		at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.archiveCorruptOrUnsupportedToast(CompressedExplorerFragment.kt:622)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.changePath$lambda-22$lambda-21(CompressedExplorerFragment.kt:583)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.$r8$lambda$fmscQU9YC5gGBMgAcmdKIXMPl08(Unknown Source:0)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment$$ExternalSyntheticLambda6.accept(Unknown Source:6)
		at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
		at android.os.Handler.handleCallback(Handler.java:942)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:211)
		at android.os.Looper.loop(Looper.java:300)
		at android.app.ActivityThread.main(ActivityThread.java:8401)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)


```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3640; @scruel please make sure that the file tried to open wasn't corrupted.

**Comment by scruel** [comment]
@VishnuSanal I can be sure they are not corrupted. And even so, the app should not just exit/crash at all.

**Comment by VishnuSanal** [comment]
> @VishnuSanal I can be sure they are not corrupted. And even so, the app should not just exit/crash at all.

Alright, thanks for the confirmation. This issue was closed because it's already being tracked.
