### ISSUE TITLE
Crash when trying to edit SFTP connection (port = empty string)

### ISSUE THREAD

**Issue by Firepal** [arpitkh96/AmazeFileManager#4122]
**Describe the bug**
App crashes Guru-Meditation-style when editing an SFTP connection (with an IPv6 adress).
(I don't use IPv4 for SFTP connections and haven't tried it yet)

**To Reproduce**
Add an SFTP cloud connection with an IPv6 address, then once created, try to edit it.

**Expected behavior**
Well.... it shouldn't crash when you try to edit the connection.

**Crash Log**
```kotlin
java.lang.NumberFormatException: For input string: ""
 at java.lang.Integer.parseInt(Integer.java:757)
 at java.lang.Integer.parseInt(Integer.java:865)
 at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.createConnectionSettings(SftpConnectDialog.kt:793)
 at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.appendButtonListenersForEdit(SftpConnectDialog.kt:276)
 at com.amaze.filemanager.ui.dialogs.SftpConnectDialog.onCreateDialog(SftpConnectDialog.kt:169)
 at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
 at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
 at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1825)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
 at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:237)
 at android.os.Looper.loop(Looper.java:335)
 at android.app.ActivityThread.main(ActivityThread.java:8140)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1054)
```

**Info**
* App Name: Amaze File Manager
* Package: com.amaze.filemanager
* Version: 3.10
* User Action: UI Error
* Request: Application crash
* OS: Linux Android 13 - 33
* Device: Civic_S
* Model: T506G
* Product: T506G_EA

**Smartphone (please complete the following information):**
 - Device: TCL 406s (firmware says 506, not important)
 - OS: Android 13
 - Rooted: Nope!
 - Version: 3.10

**Comment by Firepal** [comment]
Whoops; unrelated to IPv6. And duplicate of #3300

**Comment by Firepal** [comment]
Nevermind, the crash log is different. Separate issue!

**Comment by Firepal** [comment]
This thing is acting up because of the `port` variable, it seems.
I didn't change it, it was 22 by default and that seemed to have worked fine.

https://github.com/TeamAmaze/AmazeFileManager/blob/7136ff3e796507310e7173308e60dab566691da4/app/src/main/java/com/amaze/filemanager/ui/dialogs/SftpConnectDialog.kt#L786-L809
