### ISSUE TITLE
just a crash cause i was poking around my phone. who ever it is doesn't like that

### ISSUE THREAD

**Issue by bearCHOPPER** [arpitkh96/AmazeFileManager#4123]
## Issue explanation (write below this line)
the biggest issue is it shouldn't say linux
cricket. my hacker hates when i start poking around. how else do i find info on getting rid of them or him/her   

hoping somebody takes notice eventually and offers assistance

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Cricket/DEMK4123/SL112C:13/TP1A.220624.014/1685194451:user/release-keys 13 - 33
* __Device:__ SL112C
* __Model:__ SL112C
* __Product:__ DEMK4123
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{24b3880} (db35a01e-1c5d-4e30-84df-92500fcce0b4) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:1013)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:249)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3288)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:681)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:647)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2382)
	at androidx.fragment.app.FragmentManager.lambda$attachController$4(FragmentManager.java:2660)
	at androidx.fragment.app.FragmentManager.$r8$lambda$sido8p6zuWx0PQxIkv4qM-BRiGM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:383)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1325)
	at android.app.Activity.performSaveInstanceState(Activity.java:2212)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1563)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5865)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5263)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5229)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5294)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7955)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #1555
