### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Cmac299203** [arpitkh96/AmazeFileManager#4129]
**Describe the bug**

**To Reproduce**
Steps to reproduce ## Issue explanation (write below this line)

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/x1qcsx/x1q:13/TP1A.220624.014/G981WVLU6HWHA:user/release-keys 13 - 33
* __Device:__ x1q
* __Model:__ SM-G981W
* __Product:__ x1qcsx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: bad base-64
	at android.util.Base64.decode(Base64.java:163)
	at android.util.Base64.decode(Base64.java:138)
	at android.util.Base64.decode(Base64.java:120)
	at com.amaze.filemanager.utils.PasswordUtil.aesDecryptPassword(PasswordUtil.kt:65)
	at com.amaze.filemanager.utils.PasswordUtil.decryptPassword(PasswordUtil.kt:124)
	at com.amaze.filemanager.filesystem.files.EncryptDecryptUtils.decryptFile(EncryptDecryptUtils.java:195)
	at com.amaze.filemanager.ui.fragments.MainFragment.onListItemClicked(MainFragment.java:496)
	at com.amaze.filemanager.adapters.RecyclerAdapter.lambda$bindViewHolderList$2(RecyclerAdapter.java:817)
	at com.amaze.filemanager.adapters.RecyclerAdapter.$r8$lambda$AZs17VrHIpbKmmzxbKvQw2FTI_E(Unknown Source:0)
	at com.amaze.filemanager.adapters.RecyclerAdapter$$ExternalSyntheticLambda3.onClick(Unknown Source:8)
	at android.view.View.performClick(View.java:7892)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30891)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>
 behavior:

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

**Comment by VishnuSanal** [comment]
dupe #3602
