### ISSUE TITLE
Crash when rotate the device after selecting a folder

### ISSUE THREAD

**Issue by XYIheng** [arpitkh96/AmazeFileManager#4133]
**Describe the bug**
long click and select some folder, then rotate device, sometimes it will crash

I test on emulator and real android device pixel 7. This bug not 100% occurs 

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 2]
 - OS: [Android 10]
 - Version: [3.10]

https://github.com/TeamAmaze/AmazeFileManager/assets/31406320/9af6f28a-1e3d-47fe-b91d-ea5a349d525e

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 10 - 29
* __Device:__ generic_x86
* __Model:__ Android SDK built for x86
* __Product:__ sdk_phone_x86
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{dc7fa5d} (31d73e78-982c-4c0a-b6cd-3d6673bd13d5) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:1013)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:249)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3288)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:681)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:647)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2382)
	at androidx.fragment.app.FragmentManager.lambda$attachController$4(FragmentManager.java:2660)
	at androidx.fragment.app.FragmentManager.$r8$lambda$sido8p6zuWx0PQxIkv4qM-BRiGM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:383)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1325)
	at android.app.Activity.performSaveInstanceState(Activity.java:2037)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1478)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5304)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4630)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5252)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5187)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #1555
