### ISSUE TITLE
App crashes when inactive on background, after screen locking

### ISSUE THREAD

**Issue by KelvinNovais** [arpitkh96/AmazeFileManager#4151]
## Issue explanation (write below this line)

Context: I use this app to access some PDFs for reading. Naturally when I open the file, Amaze goes to the background. If after sometime the screen get locked or I do that myself, the following crash is reported when unlocking the screen.

I tried to figure out more precisely the causes, but I only can highlight these 3 conditions:

1. The app is running on the background;
2. It's inactive for some time;
3. The screen got locked.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux motorola/nora_row/nora_8917:8.0.0/OPP27.91-176-11/7:user/release-keys 8.0.0 - 26
* __Device:__ nora_8917
* __Model:__ moto e5
* __Product:__ nora_row
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{396a2e1} (60c17d3b-4e21-45ee-b417-d731259163b1) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:1013)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:249)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3288)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:681)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:647)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2382)
	at androidx.fragment.app.FragmentManager.lambda$attachController$4(FragmentManager.java:2660)
	at androidx.fragment.app.FragmentManager.$r8$lambda$sido8p6zuWx0PQxIkv4qM-BRiGM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:383)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1325)
	at android.app.Activity.performSaveInstanceState(Activity.java:1500)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1407)
	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4897)
	at android.app.ActivityThread.handleSleeping(ActivityThread.java:4348)
	at android.app.ActivityThread.-wrap23(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6694)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
thanks for reporting, but this issue is already been tracked via #1555. please follow that issue for updates, thanks. closing this for now
