### ISSUE TITLE
Sorting by relevance when search fails causes crash

### ISSUE THREAD

**Issue by Mo-1996** [arpitkh96/AmazeFileManager#4182]
**Describe the bug**
I failed the search and selected the type to sort by relevance. When I clicked on ascending, the app crashed. 
In additon, I searched for files located under sub files, but no results were presented

**To Reproduce**
1. Go to Search page
2. Search for files, no results presented
3. Click the "Sort By: Relevance"
4. Select the type and click "ASCENDING"
5. See error

**Expected behavior**
The app is running normally.

**Screenshots**
[crash.webm](https://github.com/TeamAmaze/AmazeFileManager/assets/46777154/bb33df84-652b-4a4a-9644-499ed3e32e48)
![image](https://github.com/TeamAmaze/AmazeFileManager/assets/46777154/461c006d-67e7-48dc-8ca8-3827d267173f)

**Smartphone (please complete the following information):**
 - Device: [e.g. Nexus 5X]
 - OS: [e.g. Android 8]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.10]

**Additional context**

**Comment by VishnuSanal** [comment]
Thanks for reporting. Please share the crash report for further debugging.

**Comment by Mo-1996** [comment]
> Thanks for reporting. Please share the crash report for further debugging.

java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at java.util.ArrayList.<init>(ArrayList.java:191)
	at com.amaze.filemanager.ui.views.appbar.SearchView.updateResultList(SearchView.java:375)
	at com.amaze.filemanager.ui.views.appbar.SearchView.onSortTypeSelected(SearchView.java:481)
	at com.amaze.filemanager.ui.views.appbar.SearchView.lambda$showSearchResultsSortDialog$10(SearchView.java:464)
	at com.amaze.filemanager.ui.views.appbar.SearchView.$r8$lambda$2i4K5Lmbv48UVtMgrOeSwx46nss(Unknown Source:0)
	at com.amaze.filemanager.ui.views.appbar.SearchView$$ExternalSyntheticLambda9.onClick(Unknown Source:2)
	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:433)
	at android.view.View.performClick(View.java:7664)
	at android.view.View.performClickInternal(View.java:7638)
	at android.view.View.access$3800(View.java:878)
	at android.view.View$PerformClick.run(View.java:29899)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9596)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

**Comment by VishnuSanal** [comment]
this is a duplicate to #4140, please track it there. :)
