### ISSUE TITLE
Rotate the screen after entering text during the search, and the text disappears

### ISSUE THREAD

**Issue by Mo-1996** [arpitkh96/AmazeFileManager#4185]
**Describe the bug**
I found an issue during the search process. After entering the text, I rotated the device and the text I just entered disappeared.

**To Reproduce**
1. Click on 'Search' button
2. Enter text and rotate the phone
3. See error

**Expected behavior**
The pages before and after rotation should remain consistent, which means that the entered text should still be on the page.

**Screenshots**
[Amaze-ro.webm](https://github.com/TeamAmaze/AmazeFileManager/assets/46777154/14501be6-591d-4144-9b82-95d569898835)

**Smartphone (please complete the following information):**
Device: [e.g. Nexus 5X]
OS: [e.g. Android 8]
Rooted: [e.g. No]
Version: [e.g. 3.10]

**Additional context**

**Comment by VishnuSanal** [comment]
Thanks for reporting. Please share the crash report for further debugging.

**Comment by Mo-1996** [comment]
> Thanks for reporting. Please share the crash report for further debugging.

java.lang.IllegalStateException: Fragment MainFragment{7500e61} (e95a0a6b-a2dc-46b2-9cf8-044facecb43a) is not currently in the FragmentManager
        at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:1013)
        at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:249)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3288)
        at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:681)
        at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:647)
        at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
        at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2382)
        at androidx.fragment.app.FragmentManager.lambda$attachController$4(FragmentManager.java:2660)
        at androidx.fragment.app.FragmentManager.$r8$lambda$sido8p6zuWx0PQxIkv4qM-BRiGM(Unknown Source:0)
        at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(Unknown Source:2)
        at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
        at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
        at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:383)
        at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1325)
        at android.app.Activity.performSaveInstanceState(Activity.java:1496)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1386)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4721)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4672)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by VishnuSanal** [comment]
this is a duplicate to #1555, please track this issue there :)
