### ISSUE TITLE
Crash when entering Interface Settings

### ISSUE THREAD

**Issue by Ketrel** [arpitkh96/AmazeFileManager#4188]
## Issue explanation (write below this line)

When I enter the interface settings, Amaze crashes with the following.
This happens every time.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 10 - 29
* __Device:__ Poke3
* __Model:__ Poke3
* __Product:__ Poke3
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: list[49] is a repetition
	at android.os.LocaleList.<init>(LocaleList.java:195)
	at androidx.core.os.LocaleListCompat$Api24Impl.createLocaleList(LocaleListCompat.java:341)
	at androidx.core.os.LocaleListCompat.create(LocaleListCompat.java:77)
	at androidx.core.os.LocaleListCompat.forLanguageTags(LocaleListCompat.java:172)
	at com.amaze.filemanager.utils.ContextLocaleExtKt.getLocaleListFromXml(ContextLocaleExt.kt:53)
	at com.amaze.filemanager.utils.ContextLocaleExtKt.getLangPreferenceDropdownEntries(ContextLocaleExt.kt:62)
	at com.amaze.filemanager.ui.fragments.preferencefragments.UiPrefsFragment.onCreatePreferences(UiPrefsFragment.kt:53)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7510)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
@TranceLove should we reopen #4088?

**Comment by maverick74** [comment]
I'm also experiencing this!!!

**Comment by VishnuSanal** [comment]
dupe #4088
