### ISSUE TITLE
Shortcut not working on app folders

### ISSUE THREAD

**Issue by pooiod** [arpitkh96/AmazeFileManager#4232]
**Describe the bug**
Using a shortcut will crash when trying to go to a folder inside of an app data folder

**To Reproduce**
1. Go to android/data/ (some app here)
2. Add a folder inside to favorites 
3. Restart app
4. Click on bookmark

**Expected behavior**
The folder opens

**Video recording**
https://file.io/gjJiitRUFq8S

**Smartphone:**
 - Device: Galaxy Note 10+
 - OS: Android 12
 - Rooted: no
 - Version: Amaze File Manager 3.10 (F-Droid)

**Additional context**
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ d2q
* __Model:__ SM-N975U
* __Product:__ d2qsq
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.amaze.filemanager.utils.OTGUtil.getDocumentFiles, parameter rootUriString
	at com.amaze.filemanager.utils.OTGUtil.getDocumentFiles(Unknown Source:12)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listDocumentFilesInternal(LoadFilesListTask.java:839)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listDocumentFiles(LoadFilesListTask.java:746)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:176)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:91)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
Dupe #2867

**Comment by VishnuSanal** [comment]
Thanks for the detailed bug report! This issue is already being reported & being tracked via #2867. Closing this.
