### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Cmac299203** [arpitkh96/AmazeFileManager#4233]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/o1qcsx/o1q:14/UP1A.231005.007/G991WVLUAGXDE:user/release-keys 14 - 34
* __Device:__ o1q
* __Model:__ SM-G991W
* __Product:__ o1qcsx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.amaze.filemanager.utils.OTGUtil.getDocumentFile, parameter rootUri
	at com.amaze.filemanager.utils.OTGUtil.getDocumentFile(Unknown Source:8)
	at com.amaze.filemanager.filesystem.HybridFile.getName(HybridFile.java:482)
	at com.amaze.filemanager.adapters.HiddenAdapter.onBindViewHolder(HiddenAdapter.kt:73)
	at com.amaze.filemanager.adapters.HiddenAdapter.onBindViewHolder(HiddenAdapter.kt:50)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #2960
