### ISSUE TITLE
APP/IU ERROR

### ISSUE THREAD

**Issue by LittlerWorm** [arpitkh96/AmazeFileManager#4243]
## Issue explanation 

Running Amaze and other one app in the same screem. Before i was create a .txt file with Amaze, them we I will open it to edit with the other information wash crassed.

##Extra info:

# Watchdog A14 VERSION 4.19.318-perf #6 SMP PREEMPT Tue Aug 20 09:14:55 EDT 2024

#Custom Kerner 4.19.275-NetErnel-v1_by@Ygrek178_base@HELLBOY017 #1 SMP PREEMPT Thu Mar 9 23:46:04 MSK 2023

#Magisk Canary 

See you!

## Exception
* __App Name:__ Administrador de Archivos Amaze
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 14 - 34
* __Device:__ OnePlus8T
* __Model:__ KB2003
* __Product:__ OnePlus8T
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{339048e} (5cd25bf3-1538-4df4-8c41-728a0c6f9006) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:1013)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:249)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3288)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:681)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:647)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2382)
	at androidx.fragment.app.FragmentManager.lambda$attachController$4(FragmentManager.java:2660)
	at androidx.fragment.app.FragmentManager.$r8$lambda$sido8p6zuWx0PQxIkv4qM-BRiGM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:383)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1325)
	at android.app.Activity.performSaveInstanceState(Activity.java:2417)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1760)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6260)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5666)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5632)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5697)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
Dupe #1555
