### ISSUE TITLE
Amaze crashes on load : Unable to load UI

### ISSUE THREAD

**Issue by darrklogik** [arpitkh96/AmazeFileManager#4259]
## Issue explanation (write below this line)
Extracted APK installs fine, but wont run on a debliated note9.. It throws an exception:

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 9 - 28
* __Device:__ crownlte
* __Model:__ SM-N960F
* __Product:__ crownltexx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: android.view.InflateException: Binary XML file line #108: Binary XML file line #108: You must supply a layout_width attribute.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: android.view.InflateException: Binary XML file line #108: Binary XML file line #108: You must supply a layout_width attribute.
Caused by: java.lang.UnsupportedOperationException: Binary XML file line #108: You must supply a layout_width attribute.
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:779)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8135)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8327)
	at androidx.drawerlayout.widget.DrawerLayout$LayoutParams.<init>(DrawerLayout.java:2319)
	at androidx.drawerlayout.widget.DrawerLayout.generateLayoutParams(DrawerLayout.java:1906)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
	at com.amaze.filemanager.ui.activities.MainActivity.onCreate(MainActivity.java:337)
	at android.app.Activity.performCreate(Activity.java:7326)
	at android.app.Activity.performCreate(Activity.java:7317)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #2105
