### ISSUE TITLE
Changing search order & such causes crash

### ISSUE THREAD

**Issue by Fau57** [arpitkh96/AmazeFileManager#4274]
## Issue explanation (write below this line)

tweaking search settings IE: name, type, last modified. when I pressed descending it crashed. hope that helps

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/r8qcsx/r8q:13/TP1A.220624.014/G781WVLUGHXG1:user/release-keys 13 - 33
* __Device:__ r8q
* __Model:__ SM-G781W
* __Product:__ r8qcsx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at java.util.ArrayList.<init>(ArrayList.java:188)
	at com.amaze.filemanager.ui.views.appbar.SearchView.updateResultList(SearchView.java:375)
	at com.amaze.filemanager.ui.views.appbar.SearchView.onSortTypeSelected(SearchView.java:481)
	at com.amaze.filemanager.ui.views.appbar.SearchView.lambda$showSearchResultsSortDialog$11(SearchView.java:469)
	at com.amaze.filemanager.ui.views.appbar.SearchView.$r8$lambda$d_i92XacrdBgqH38-DZKwptUe_8(Unknown Source:0)
	at com.amaze.filemanager.ui.views.appbar.SearchView$$ExternalSyntheticLambda10.onClick(Unknown Source:2)
	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16220)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30891)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #4140
