### ISSUE TITLE
Cannot open files (zip archive) in termux home folder

### ISSUE THREAD

**Issue by 0dminnimda** [arpitkh96/AmazeFileManager#4279]
## Issue explanation (write below this line)

Cannot open files (zip archive) in termux home folder

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ yunluo
* __Model:__ 22081283G
* __Product:__ yunluo_global
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:82)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8266)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
  ComposedException 1 :
	org.apache.commons.compress.archivers.ArchiveException: Zip file is corrupt
		at com.amaze.filemanager.asynchronous.asynctasks.compress.ZipHelperCallable.addElements(ZipHelperCallable.kt:129)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperCallable.call(CompressedHelperCallable.kt:46)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperCallable.call(CompressedHelperCallable.kt:31)
		at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:39)
		at io.reactivex.Flowable.subscribe(Flowable.java:14826)
		at io.reactivex.Flowable.subscribe(Flowable.java:14773)
		at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
		at java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
		at java.lang.Thread.run(Thread.java:1012)
	Caused by: net.lingala.zip4j.exception.ZipException: Zip file size less than minimum expected zip file size. Probably not a zip file or a corrupted zip file
		at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:68)
		at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:971)
		at net.lingala.zip4j.ZipFile.getFileHeaders(ZipFile.java:559)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.ZipHelperCallable.filterValidEntryList(ZipHelperCallable.kt:134)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.ZipHelperCallable.addElements(ZipHelperCallable.kt:54)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperCallable.call(CompressedHelperCallable.kt:46)
		at com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperCallable.call(CompressedHelperCallable.kt:31)
		at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:39)
		at io.reactivex.Flowable.subscribe(Flowable.java:14826)
		at io.reactivex.Flowable.subscribe(Flowable.java:14773)
		at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
		at java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
		at java.lang.Thread.run(Thread.java:1012)
	Caused by: java.lang.IllegalStateException: Fragment CompressedExplorerFragment{2fc14cb} (2ecf43a1-5c42-4798-ae5f-4cac93bc7195) not attached to a context.
		at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.archiveCorruptOrUnsupportedToast(CompressedExplorerFragment.kt:635)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.access$archiveCorruptOrUnsupportedToast(CompressedExplorerFragment.kt:93)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment$changePath$1$2.invoke(CompressedExplorerFragment.kt:594)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment$changePath$1$2.invoke(CompressedExplorerFragment.kt:585)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.changePath$lambda$22$lambda$21(CompressedExplorerFragment.kt:590)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.$r8$lambda$zYX3lQKoIEqZveznYCFYf8Yz_6Y(Unknown Source:0)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment$$ExternalSyntheticLambda3.accept(Unknown Source:2)
		at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:211)
		at android.os.Looper.loop(Looper.java:300)
		at android.app.ActivityThread.main(ActivityThread.java:8266)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
  ComposedException 2 :
	java.lang.IllegalStateException: Fragment CompressedExplorerFragment{2fc14cb} (2ecf43a1-5c42-4798-ae5f-4cac93bc7195) not attached to a context.
		at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.archiveCorruptOrUnsupportedToast(CompressedExplorerFragment.kt:635)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.access$archiveCorruptOrUnsupportedToast(CompressedExplorerFragment.kt:93)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment$changePath$1$2.invoke(CompressedExplorerFragment.kt:594)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment$changePath$1$2.invoke(CompressedExplorerFragment.kt:585)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.changePath$lambda$22$lambda$21(CompressedExplorerFragment.kt:590)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.$r8$lambda$zYX3lQKoIEqZveznYCFYf8Yz_6Y(Unknown Source:0)
		at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment$$ExternalSyntheticLambda3.accept(Unknown Source:2)
		at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
		at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:211)
		at android.os.Looper.loop(Looper.java:300)
		at android.app.ActivityThread.main(ActivityThread.java:8266)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)


```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3640 & #1555
