### ISSUE TITLE
Crash report (crashed in the background) 

### ISSUE THREAD

**Issue by Aadam-Marshall** [arpitkh96/AmazeFileManager#4281]
## Issue explanation
I didn't do anything, it just crashed in the background. 

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/a34xdxx/a34x:14/UP1A.231005.007/A346EXXU8CXG8:user/release-keys 14 - 34
* __Device:__ a34x
* __Model:__ SM-A346E
* __Product:__ a34xdxx
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Parameter specified as non-null is null: method com.amaze.trashbin.TrashBinFile.<init>, parameter fileName
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	at io.reactivex.internal.operators.completable.CompletableFromRunnable.subscribeActual(CompletableFromRunnable.java:40)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.amaze.trashbin.TrashBinFile.<init>, parameter fileName
	at com.amaze.trashbin.TrashBinFile.<init>(Unknown Source:2)
	at com.amaze.filemanager.filesystem.HybridFile.toTrashBinRestoreFile(HybridFile.java:1856)
	at com.amaze.filemanager.filesystem.HybridFile.deletePermanentlyFromBin(HybridFile.java:1596)
	at com.amaze.filemanager.filesystem.HybridFile.delete(HybridFile.java:1543)
	at com.amaze.filemanager.application.AppConfig.lambda$getTrashBinInstance$2(AppConfig.java:285)
	at com.amaze.filemanager.application.AppConfig.$r8$lambda$hMGiVDvfwwzG3tz2_fRQ8F7OGvY(Unknown Source:0)
	at com.amaze.filemanager.application.AppConfig$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at io.reactivex.internal.operators.completable.CompletableFromRunnable.subscribeActual(CompletableFromRunnable.java:36)
	... 10 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #4135
