### ISSUE TITLE
Crashes when opening a folder

### ISSUE THREAD

**Issue by AmrAlSayed0** [arpitkh96/AmazeFileManager#4286]
## Issue explanation (write below this line)

Crashes with this exception when opening a folder

## Exception
* __App Name:__ File Manager
* __Package:__ com.filemanager.lnapp
* __Version:__ 3.5.97
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 10 - 29
* __Device:__ beryllium
* __Model:__ POCOPHONE F1
* __Product:__ beryllium
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NumberFormatException: For input string: "1732774532 | frc_1:153233709837:android:574404ccd17ba4551bee44_firebase_activate.json"
	at java.lang.Long.parseLong(Long.java:594)
	at java.lang.Long.parseLong(Long.java:636)
	at com.amaze.filemanager.filesystem.files.FileUtils.parseName(FileUtils.java:942)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.parseStringForHybridFile(ListFilesCommand.kt:222)
	at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:60)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:265)
	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:78)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
dupe #3359
