### ISSUE TITLE
What is this 

### ISSUE THREAD

**Issue by Snowwbugg12** [arpitkh96/AmazeFileManager#4287]
## Exception
* __App Name:__ File Manager
* __Package:__ com.alc.filemanager
* __Version:__ 10.0
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ N6001LA
* __Model:__ N6001L
* __Product:__ N6001L1
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service com.amaze.filemanager.asynchronous.services.ftp.FtpService@8f7ecea with Intent { cmp=com.alc.filemanager/com.amaze.filemanager.asynchronous.services.ftp.FtpService }: java.lang.IllegalArgumentException: com.alc.filemanager: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4743)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2218)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7941)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
Caused by: java.lang.IllegalArgumentException: com.alc.filemanager: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
	at android.app.PendingIntent.getActivity(PendingIntent.java:470)
	at android.app.PendingIntent.getActivity(PendingIntent.java:434)
	at com.amaze.filemanager.ui.notifications.FtpNotification.buildNotification(FtpNotification.java:51)
	at com.amaze.filemanager.ui.notifications.FtpNotification.startNotification(FtpNotification.java:84)
	at com.amaze.filemanager.asynchronous.services.ftp.FtpService.onStartCommand(FtpService.kt:101)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4725)
	... 9 more

```
</details>
<hr>
Android 10 
Non rooted .

**Comment by VishnuSanal** [comment]
you are not using the official version of amaze. please doanload from the official sources.
