### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by kashmino** [arpitkh96/AmazeFileManager#4291]
**Describe the bug**
Crashes after turning screen back on
**To Reproduce**
1.turn on and off screen.
2. 
3. 

**Expected behavior**
Restart normally, no error screen
**Screenshots**

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 15 - 35
* __Device:__ lynx
* __Model:__ Pixel 7a
* __Product:__ lynx
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{535b76c} (aeb1c084-3f66-4ecd-9754-bf7e7827a467) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:1013)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:250)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3288)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:681)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:647)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2382)
	at androidx.fragment.app.FragmentManager.lambda$attachController$4(FragmentManager.java:2660)
	at androidx.fragment.app.FragmentManager.$r8$lambda$sido8p6zuWx0PQxIkv4qM-BRiGM(Unknown Source:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:383)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1325)
	at android.app.Activity.performSaveInstanceState(Activity.java:2431)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1754)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6320)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5728)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5694)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5758)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:107)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

```
</details>
<hr>

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: [e.g. Android
 - Rooted: [e.g. No]
 - Version: 

**Additional context**

**Comment by VishnuSanal** [comment]
Dupe #1555
