### ISSUE TITLE
App Crashes When Sorting After Empty Search Results

### ISSUE THREAD

**Issue by ScenarioKG** [arpitkh96/AmazeFileManager#4301]
**Describe the bug**
The app crashes when attempting to sort search results after an empty search query.

**To Reproduce**
1. Click on 'Search' icon
2. Type a search query that returns no results (e.g., ‘desired search query’).
3. Click on 'Sort by' button
4. Click on either the ‘ASCENDING’ or ‘DESCENDING’ button.
 
**Expected behavior**
The app should not crash when sorting search results, even if no results are found.

**Video**

https://github.com/user-attachments/assets/585cc451-5fb4-4a0f-a7b7-1e0181bbc0df

**Smartphone (please complete the following information):**
- Device: [Google Pixel 5]
- OS: [Android 14]
- Rooted: [No]
- Version: [3.10]

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 14 - 34
* __Device:__ redfin
* __Model:__ Pixel 5
* __Product:__ redfin
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at java.util.ArrayList.<init>(ArrayList.java:188)
	at com.amaze.filemanager.ui.views.appbar.SearchView.updateResultList(SearchView.java:375)
	at com.amaze.filemanager.ui.views.appbar.SearchView.onSortTypeSelected(SearchView.java:481)
	at com.amaze.filemanager.ui.views.appbar.SearchView.lambda$showSearchResultsSortDialog$11(SearchView.java:469)
	at com.amaze.filemanager.ui.views.appbar.SearchView.$r8$lambda$d_i92XacrdBgqH38-DZKwptUe_8(Unknown Source:0)
	at com.amaze.filemanager.ui.views.appbar.SearchView$$ExternalSyntheticLambda10.onClick(Unknown Source:2)
	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```
</details>
<hr>

**Comment by VishnuSanal** [comment]
thanks for reporting. dupe #4140 & fixed with #4222. will be rolled in the next release.
