### ISSUE TITLE
`IllegalStateException`: Attempting to launch an unregistered `ActivityResultLauncher`

### ISSUE THREAD

**Issue by mengqianX** [arpitkh96/AmazeFileManager#4317]
## Exception
App Name: Amaze File Manager
Version: 3.10
User Action: UI Error
Request: Application crash
OS: Linux Android 11 - 30
Device: Google Nexus 4

<details>
<summary> crash log </summary>

```
java.lang.IllegalStateException: Attempting to launch an unregistered ActivityResultLauncher with contract androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult@26ceea5 and input Intent { act=android.intent.action.OPEN_DOCUMENT_TREE (has extras) }. You must ensure the ActivityResultLauncher is registered before calling launch().
        at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:168)
        at androidx.fragment.app.Fragment$10.launch(Fragment.java:3612)
        at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
        at com.amaze.filemanager.ui.fragments.MainFragment.lambda$loadPathInQ$4$com-amaze-filemanager-ui-fragments-MainFragment(MainFragment.java:731)
        at com.amaze.filemanager.ui.fragments.MainFragment$$ExternalSyntheticLambda13.run(Unknown Source:4)
        at com.amaze.filemanager.ui.ExtensionsKt.runIfDocumentsUIExists(Extensions.kt:124)
        at com.amaze.filemanager.ui.fragments.MainFragment.lambda$loadPathInQ$5$com-amaze-filemanager-ui-fragments-MainFragment(MainFragment.java:728)

        at com.amaze.filemanager.ui.fragments.MainFragment$$ExternalSyntheticLambda7.onClick(Unknown Source:6)

        at android.view.View.performClick(View.java:7448)

        at android.view.View.performClickInternal(View.java:7425)

        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
</details>

**Comment by EmmanuelMess** [comment]
@VishnuSanal any idea when this happens? Is it using Amaze to choose a file?

**Comment by VishnuSanal** [comment]
yes, I think this occurs due to missing `DocumentsUI`. this is similar to #2417 (and #3571). should do the same fix on `MainFragment#loadPathInQ` also.
