### ISSUE TITLE
Copying a few folders crashes

### ISSUE THREAD

**Issue by EmmanuelMess** [arpitkh96/AmazeFileManager#523]
Copying WhatsApp's folders to a directory that already has those folders (to combine them) produced this crash, I'll start trying to solve this tomorrow. Android 6.0 Moto E2 4G

    04-15 15:48:27.558 18184-18503/com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: service_startup_watcher
                                                                            Process: com.amaze.filemanager, PID: 18184
                                                                            java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                                                at java.util.ArrayList.remove(ArrayList.java:405)
                                                                                at com.amaze.filemanager.utils.ServiceWatcherUtil$2.run(ServiceWatcherUtil.java:156)
                                                                                at android.os.Handler.handleCallback(Handler.java:746)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by vishal0071** [comment]
This is a race condition I tried to minimize it's reproduction due to your clashing algorithm. I don't think It can be minimized further without changing either your filename clashing algorithm and changing how service work. 
It's hard to reproduce now anyways. I would recommend to let it pass. It's not worth the time.

**Comment by vishal0071** [comment]
While typing a reply to you, I laughed at myself for not simply using a synchronized access modifier to avoid race condition. 
Thanks to this issue, now this problem is possibly fixed.

**Comment by vishal0071** [comment]
Did you try reproducing it on v3.1.2 Beta 10?

**Comment by EmmanuelMess** [comment]
Doesn't crash anymore. Closing :)
