### ISSUE TITLE
Can't cut nor copy more than one item

### ISSUE THREAD

**Issue by EmmanuelMess** [arpitkh96/AmazeFileManager#644]
Cut:
```
06-24 12:35:47.931 12262-12262/com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.amaze.filemanager, PID: 12262
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'com.amaze.filemanager.filesystem.BaseFile com.amaze.filemanager.ui.LayoutElement.generateBaseFile()' on a null object reference
                                                                           at com.amaze.filemanager.fragments.MainFragment$5.onActionItemClicked(MainFragment.java:775)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImplV9.java:1801)
                                                                           at android.support.v7.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
                                                                           at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                           at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                           at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                           at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
                                                                           at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
                                                                           at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
                                                                           at android.view.View.performClick(View.java:5201)
                                                                           at android.view.View$PerformClick.run(View.java:21163)
                                                                           at android.os.Handler.handleCallback(Handler.java:746)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```
Copy:
```
06-24 12:40:06.553 15087-15087/com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.amaze.filemanager, PID: 15087
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'com.amaze.filemanager.filesystem.BaseFile com.amaze.filemanager.ui.LayoutElement.generateBaseFile()' on a null object reference
                                                                           at com.amaze.filemanager.fragments.MainFragment$5.onActionItemClicked(MainFragment.java:765)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImplV9.java:1801)
                                                                           at android.support.v7.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
                                                                           at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                           at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                           at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                           at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
                                                                           at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
                                                                           at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
                                                                           at android.view.View.performClick(View.java:5201)
                                                                           at android.view.View$PerformClick.run(View.java:21163)
                                                                           at android.os.Handler.handleCallback(Handler.java:746)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by EmmanuelMess** [comment]
Can't replicate anymore
